# Generated by Django 4.1.2 on 2022-11-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoderhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-last_update']},
        ),
    ]
